### ISSUE TITLE
Setup demo app as a part of github.io pages

### ISSUE THREAD

**Issue by Zatvobor** [ember-insights/ember-insights#46]
#### steps:
- [x] Setup `gh-pages` and ember available assets
- [x] Bootstrap application UI
- [x] Implement first class application workflow
- [x] Plugging `ember-insights` as a Bower package, #72
- [x] Integrate application's interface w/ `ember-insights` (ConsoleTracker)
- [x] Get application ready for plugging as a Web Component from `index.html`
- [x] Choose appropriate design template for `index.thml` and use it
- [x] Choose appropriate javascript highlither and use it for `app.js`

#### app skitch:
![img_1588 2015-01-30 19-27-54](https://cloud.githubusercontent.com/assets/69053/5980133/28790816-a8b6-11e4-8d30-51810ed7a2c3.jpg)

**Comment by Zatvobor** [comment]
UP http://roundscope.github.io/ember-insights
